<!doctype html> 
    <html> 
    <?php require_once('partials/header.html'); ?>
    <body> 
    <?php require_once('partials/banner.html'); ?>

<div class="container"> 
    <div class="row"> 
        <?php require_once('partials/navigation.html'); ?>
        <div class="col-9"> 
            <div class="row"> 
                <form action="/receipt" class="col-12 form-horizontal" method="post">  <h3>Confirm Browser Payment</h3> 
                    <fieldset> 

                        <input type="hidden" readonly="readonly" name="apiOperation" value="CONFIRM_BROWSER_PAYMENT" size="20" maxlength="80"/>
                        <input type="hidden" readonly="readonly" name="method" value="PUT" size="20" maxlength="80"/>
                        <div class="form-group">  <label class="col-md-7 control-label" for="orderId">Order ID</label> 
                            <div class="col-md-7"> 
                                <input id= "orderId" required="" class="form-control input-md"  type="text" name="orderId" value="" size="8" maxlength="13" placeholder="[ORDER ID FROM EXISTING TRANSACTION]"/>
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="transactionId">Transaction ID (Auto generated unique Transaction ID)</label> 
                            <div class="col-md-7"> 
                                <input id="transactionId" class="form-control input-md" type="text" size="19" maxlength="80"   name="transactionId" value="<?php echo 'trans-' . rand() ?>"/> 
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="browserPayment[returnUrl]">Return URL</label> 
                            <div class="col-md-7"> 
                                <input id="browserPayment[returnUrl]" class="form-control input-md"  type="text" name="browserPayment[returnUrl]" value="" size="1" maxlength="2"/>
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="order[amount]">Amount</label> 
                            <div class="col-md-7"> 
                                <input id= "order[amount]" required="" class="form-control input-md"  type="text" name="order[amount]" value="" size="8" maxlength="13"/>
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="transaction[currency]">Currency</label> 
                            <div class="col-md-7">
                                <input class="form-control input-md" id="transaction[currency]"  type="text" name="order[currency]" value="<?= $currency ?>"  size="8" maxlength="3"/>
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="process"></label> 
                            <div class="col-md-7"> 
                                <button id="process" name="process" class="btn btn-primary">Confirm Browser Payment</button>
                                 
                            </div>
                             
                        </div>
                         
                    </fieldset>
                     
                </form>
                 
            </div>
             
        </div>
         
    </div>
     
</div>
 
</body>
 
</html> 
