<!doctype html> 
<html> 
<?php require_once('partials/header.html'); ?>
<body> 
<?php require_once('partials/banner.html'); ?>
<div class="container"> 
    <div class="row"> 
        <?php require_once('partials/navigation.html'); ?>
        <div class="col-9"> 
            <div class="row"> 

                <div class="col-9 pl-4">
                    <h3><?= $apiOperation ?>&nbsp;Operation</h3>
                    <p class="endpoint"><?= $method ?>&nbsp;<?= $requestUrl ?></p>

                    <h5>Payload</h5>
                    <pre><?= $requestData ?></pre>
                    <h5>Response</h5>
                    <pre><?= $responseData ?></pre>
                </div>
            </div>
        </div>
    </div>
</div>
 <?php require_once('partials/spinner.html'); ?>

</body>
</html> 
