<!doctype html> 
<html> 
<?php require_once('partials/header.html'); ?>
<body> 
<?php require_once('partials/banner.html'); ?>
<div class="container"> 
    <div class="row"> 
        <?php require_once('partials/navigation.html'); ?>
        <div class="col-9"> 
            <div class="row"> 
                <div class="alert alert-warning" role="alert">
                    <p class="mb-0">This is a Customized ACS Redirect form, you my choose to redirect automatically by using a Simple Redirect, more details <a href="<?= $baseURL . 'api/documentation/integrationGuidelines/supportedFeatures/pickAdditionalFunctionality/3DS/3DSAuthentication.html#x_3DSCheckEnrollment'?>" target="_blank">here.</a> </p>
                </div>
                <form name="3dsRedirect" action="<?= $acsUrl ?>" method="POST" accept-charset="UTF-8">

                    <!-- Populate the mandatory PaReq parameter with the value returned in the 3DSecure.authenticationRedirect.customized.paReq response parameter.  -->

                    <input type="hidden" name="PaReq" value="<?= $PaReq ?>"/>

                    <!-- Populate the mandatory TermUrl value with the URL to which you want the payer returned when the authentication process has completed. This should be the same value as supplied in the 3DSecure.authenticationRedirect.responseUrl  parameter to the CHECK_ENROLLMENT request. -->

                    <input type="hidden" name="TermUrl" value="<?= $responseUrl ?>"/>

                    <!-- The ACS will echo the contents of the mandatory MD parameter when the payer is returned to the URL specified in the TermUrl parameter.  You can use this parameter to establish a link between the ACS request and response. -->

                    <input type="hidden" name="MD" value="<?= $mdValue ?>"/>
                    <div class="form-group">  <label class="col-md-7 control-label" for="process"></label> 
                        <div class="col-md-7"> 
<!--                            <input type="submit" value="Click  here to continue" class="button">-->
                            <button id="process" name="process" class="btn btn-primary">Click Here to Continue</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html> 
