<!doctype html> 
<html> 
<?php require_once('partials/header.html'); ?>
<body> 
<?php require_once('partials/banner.html'); ?>

<div class="container"> 
    <div class="row"> 
        <?php require_once('partials/navigation.html'); ?>

         
        <div class="col-9"> 
            <div class="row"> 
                <form action="/receipt" class="col-12 form-horizontal" method="post">  <h3>Verify</h3> 
                    <fieldset> 
                        <input type="hidden" readonly="readonly" name="apiOperation" value="VERIFY" size="20" maxlength="80"/>
                        <input type="hidden" readonly="readonly" name="method" value="PUT" size="20" maxlength="80"/>
                        <div class="form-group">  <label class="col-md-7 control-label" for="order-id">Order ID (Auto generated unique Order ID)</label> 
                            <div class="col-md-7"> 
                                <input id="order-id" class="form-control input-md" type="text" size="19" maxlength="80"   name="orderId" value="<?php echo 'order-' . bin2hex(openssl_random_pseudo_bytes(8)) ?>"/> 
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="transactionId">Transaction ID (Auto generated unique Transaction ID)</label> 
                            <div class="col-md-7"> 
                                <input id="transactionId" class="form-control input-md" type="text" size="19" maxlength="80"   name="transactionId" value="<?php echo 'trans-' . bin2hex(openssl_random_pseudo_bytes(8)) ?>"/> 
                            </div>
                        </div>
                        <div class="form-group">  <label class="col-md-7 control-label" for="funds-type">Source of Funds</label> 
                            <div class="col-md-7"> 
                                <input id="funds-type" class="form-control input-md" type="text" name="sourceOfFunds[type]" value="CARD" size="19" maxlength="80" readonly/>
                            </div>
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="card-number">Card Number</label> 
                            <div class="col-md-7"> 
                                <input id="card-number" type="text" class="form-control input-md" name="sourceOfFunds[provided][card][number]" value="" size="19" maxlength="80"/>
                                 </div>
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="expiry-month">Expiry Month</label> 
                            <div class="col-md-7"> 
                                <input id="expiry-month" class="form-control input-md"  type="text" name="sourceOfFunds[provided][card][expiry][month]" value="" size="1" maxlength="2"/>
                            </div>

                             
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="expiry-year">Expiry Year</label> 
                            <div class="col-md-7"> 
                                <input id="expiry-year" class="form-control input-md" type="text" name="sourceOfFunds[provided][card][expiry][year]" value="" size="1" maxlength="2"/>
                            </div>
                             
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="security-code">Security Code</label> 
                            <div class="col-md-7"> 
                                <input type="text" id="security-code" class="form-control input-md"  name="sourceOfFunds[provided][card][securityCode]" value="" size="8" maxlength="4"/>
                            </div>
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="transaction[amount]">Amount</label> 
                            <div class="col-md-7"> 
                                <input id= "transaction[amount]" required="" class="form-control input-md"  type="text" name="order[amount]" value="" size="8" maxlength="13"/>
                            </div>
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="transaction[currency]">Currency</label> 
                            <div class="col-md-7">
                                <input class="form-control input-md" id="transaction[currency]"  type="text" name="order[currency]" value="<?= $currency ?>"  size="8" maxlength="3"/>
                            </div>
                        </div>
                         
                        <div class="form-group">  <label class="col-md-7 control-label" for="process"></label> 
                            <div class="col-md-7"> 
                                <button id="process" name="process" class="btn btn-primary">Verify</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
     
</div>
  <?php require_once('partials/spinner.html'); ?>

</body>
 
</html> 
